apiVersion: v1
kind: Namespace
metadata:
  name: ml-churn
---
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: ml-churn
  annotations:
    serving.kserve.io/s3-endpoint: s3.amazonaws.com
    serving.kserve.io/s3-usehttps: "1"
    serving.kserve.io/s3-region: eu-north-1
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: "AKIA2IMXZJORWNRYAWL7"
  AWS_SECRET_ACCESS_KEY: "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"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-s3-access
  namespace: ml-churn
secrets:
  - name: s3-secret
